#!/usr/bin/env bash
# PreToolUse(Write|Edit) guard: deny hand-edits to generated Prisma output or to a
# migration that's already committed (a strong proxy for "already applied"). A brand-new,
# not-yet-committed migration.sql from `prisma migrate dev --create-only` is deliberately
# NOT blocked here — the schema-change skill requires hand-editing exactly that file to add
# SQL Prisma's schema language can't express (CHECK constraints, NULLS NOT DISTINCT),
# before it is ever applied. See AGENTS.md section 2 step 3.
set -euo pipefail

input=$(cat)
path=$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty')
[ -z "$path" ] && exit 0

case "$path" in
  */src/generated/prisma/*|src/generated/prisma/*)
    reason="src/generated/prisma/** is generated by 'pnpm db:generate' — edit prisma/schema/*.prisma instead and regenerate (AGENTS.md section 2 step 3, the schema-change skill)."
    jq -n --arg reason "$reason" \
      '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$reason}}'
    exit 0
    ;;
  */prisma/migrations/*|prisma/migrations/*)
    if git ls-files --error-unmatch -- "$path" >/dev/null 2>&1; then
      reason="this migration is already committed (a strong signal it's already applied) — never hand-edit it. A change Prisma's schema language can't express goes into a NEW migration via 'prisma migrate dev --create-only' before it's applied (AGENTS.md section 2 step 3, the schema-change skill)."
      jq -n --arg reason "$reason" \
        '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$reason}}'
    fi
    exit 0
    ;;
esac
